import folium
>>> map = folium.Map
>>> map = folium.Map(location = [51.5, -0.13])
>>> map.save('firstMap.html')
>>> map = folium.Map(location = [51.5, -0.13], zoom_start = 4)
>>> map.save('firstMap.html')
>>> map = folium.Map(location = [51.5, -0.13], zoom_start = 5)
>>> map.save('firstMap.html')
>>> map = folium.Map(location = [54, -4.4], zoom_start = 6)
>>> map.save('firstMap.html')
>>> map = folium.Map(location = [56. -4-4], zoom_start = 6)
>>> map.save('firstMap.html')
>>> map = folium.Map(location = [56, -4.4], zoom_start = 6)
>>> map.save('firstMap.html')
>>> map = folium.Map(location = [55, -4.4], zoom_start = 6)
>>> map.save('firstMap.html')
